package com.bubblewrap.notifications.alert;

public enum AlertType {
	DIVIDEND,
	EARNINGS,
	STOCK_PRICE_LIMIT,
	OPTION_PRICE_LIMIT,
	DAY_OVER_DAY,
	EOD_STOCK_PRICE_LOAD,
	DAILY_OPTIONS_LOAD,
	EARNINGS_LOAD,
	DB_BACKUP,
	OPTION_COPY_FORWARD,
	STOCK_COPY_FORWARD,
	ADMIN
}
